import React from 'react';
import { motion } from 'framer-motion';
import {
  Rocket,
  Target,
  Cpu,
  Award,
  ArrowRight,
  Play,
  Users,
  Star,
  CheckCircle2,
  BrainCircuit,
  MessageSquare,
  Trophy,
  BookOpen
} from 'lucide-react';
import { Link } from 'react-router-dom';
import './LandingPage.css';

const LandingPage = () => {
  const features = [
    {
      icon: <BrainCircuit size={32} color="#60a5fa" />,
      title: "AI Powered Tutor",
      description: "Personalized learning paths generated by advanced AI to match your pace and style."
    },
    {
      icon: <Trophy size={32} color="#facc15" />,
      title: "Quizzes & Badges",
      description: "Interactive quizzes with instant feedback. Earn badges as you master new skills."
    },
    {
      icon: <MessageSquare size={32} color="#c084fc" />,
      title: "24/7 AI Assistance",
      description: "Never get stuck again. Our AI is always online to answer any coding doubts."
    },
    {
      icon: <CheckCircle2 size={32} color="#4ade80" />,
      title: "Certifications",
      description: "Get industry-recognized certificates for every course you successfully complete."
    }
  ];

  return (
    <div className="landing-wrapper">
      {/* Hero Section */}
      <section className="hero-section">
        <div className="max-width hero-grid">
          <motion.div
            initial={{ opacity: 0, x: -50 }}
            whileInView={{ opacity: 1, x: 0 }}
            className="hero-content"
          >
            {/* <div className="badge-wrapper">
              <Rocket size={16} /> <span>Next-Gen Learning Platform</span>
            </div> */}

            <h1 className="hero-title">
              Learn <span>Smarter</span> with <br />
              <span>AI Powered</span> Education
            </h1>

            <p className="hero-desc">
              Master industry-leading skills with personalized curriculum, smart quizzes, and a supportive AI tutor that guides you at every step.
            </p>

            <div className="hero-actions">
              <Link to="/courses" className="btn-primary">
                Explore Courses <ArrowRight size={20} />
              </Link>
              <Link to="/features" className="btn-secondary">
                <Play size={20} /> Watch Demo
              </Link>
            </div>

            <div className="social-proof">
              <div className="avatars">
                {[1, 2, 3, 4].map(i => <div key={i} className="avatar-mock" style={{ zIndex: 5 - i }}>{i * 10}k+</div>)}
              </div>
              <p className="social-text">Join <strong>40,000+</strong> happy learners</p>
            </div>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            whileInView={{ opacity: 1, scale: 1 }}
            className="hero-visual"
          >
            <div className="floating-stack">
              {/* Card 1: Course Progress */}
              <motion.div 
                animate={{ y: [0, -15, 0], x: [0, 5, 0] }}
                transition={{ duration: 5, repeat: Infinity, ease: 'easeInOut' }}
                className="floating-card c1 glass-panel"
              >
                <div className="card-top">
                  <div className="icon-pill bg-blue-glow"><BrainCircuit size={18} /></div>
                  <span className="card-tag">Active Mission</span>
                </div>
                <h4 className="card-inner-title">Advanced React Ops</h4>
                <div className="progress-mini-track">
                  <div className="progress-mini-fill" style={{ width: '85%' }}></div>
                </div>
                <div className="card-footer">85% Complete</div>
              </motion.div>

              {/* Card 2: Community Stats */}
              <motion.div 
                animate={{ y: [0, 20, 0], x: [0, -10, 0] }}
                transition={{ duration: 6, repeat: Infinity, ease: 'easeInOut', delay: 1 }}
                className="floating-card c2 glass-panel"
              >
                <div className="card-top">
                  <div className="icon-pill bg-purple-glow"><Users size={18} /></div>
                  <span className="card-tag">Network</span>
                </div>
                <div className="stat-giant">40K+</div>
                <p className="stat-desc">Active Neural Nodes</p>
              </motion.div>

              {/* Card 3: New Drop */}
              <motion.div 
                animate={{ scale: [1, 1.05, 1], y: [0, 10, 0] }}
                transition={{ duration: 7, repeat: Infinity, ease: 'easeInOut', delay: 0.5 }}
                className="floating-card c3 glass-panel"
              >
                <div className="card-top">
                  <div className="icon-pill bg-green-glow"><Rocket size={18} /></div>
                  <span className="card-tag">New Stream</span>
                </div>
                <h4 className="card-inner-title">LLM Fine-tuning</h4>
                <p className="card-instr">Instructor: Neural AI</p>
              </motion.div>

              {/* Decorative Orbs */}
              <div className="visual-orb orb-1"></div>
              <div className="visual-orb orb-2"></div>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="stats-section">
        <div className="max-width stats-flex">
          {[
            { label: "Active Courses", val: "500+" },
            { label: "Expert Mentors", val: "120+" },
            { label: "Total Students", val: "40K+" },
            { label: "Course Ratings", val: "4.9/5" }
          ].map((stat, i) => (
            <div key={i} className="stat-item">
              <div className="stat-val">{stat.val}</div>
              <div className="stat-label">{stat.label}</div>
            </div>
          ))}
        </div>
      </section>

      {/* Features Grid */}
      <section className="features-section">
        <div className="max-width">
          <div className="section-header">
            <h2 className="section-title">Built for the <span>Modern Learner</span></h2>
            <p className="section-desc">Our platform combines cutting-edge AI technology with peerless educational content to accelerate your specialized growth.</p>
          </div>

          <div className="grid-4">
            {features.map((f, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.1 }}
                className="card"
              >
                <div className="card-icon-box">{f.icon}</div>
                <h3 className="card-title">{f.title}</h3>
                <p className="card-desc">{f.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
};

export default LandingPage;
